# Generated by Django 2.1.7 on 2019-04-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
                ('PostedBy', models.CharField(max_length=100)),
                ('PostedOn', models.DateField()),
                ('Description', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=10)),
                ('Location', models.CharField(max_length=100)),
                ('IMG1', models.ImageField(upload_to='media/')),
                ('IMG2', models.ImageField(upload_to='media/')),
                ('IMG3', models.ImageField(upload_to='media/')),
            ],
            options={
                'db_table': 'Details',
            },
        ),
    ]
