# Generated by Django 2.1.7 on 2019-04-08 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addetails',
            old_name='Type',
            new_name='Category',
        ),
    ]
