# Generated by Django 2.1.7 on 2019-04-08 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190409_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addetails',
            name='IMG2',
        ),
        migrations.RemoveField(
            model_name='addetails',
            name='IMG3',
        ),
    ]
