# Generated by Django 2.1.7 on 2019-04-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_signupuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signupuser',
            table='User_Reg',
        ),
    ]
