# Generated by Django 2.1.7 on 2019-04-14 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190412_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='postAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=10)),
                ('Ad_title', models.CharField(max_length=25)),
                ('Description', models.CharField(max_length=100)),
                ('Ad_Location', models.CharField(max_length=40)),
                ('Address', models.CharField(max_length=70)),
                ('Posted_Date', models.DateTimeField(default=datetime.datetime(2019, 4, 14, 19, 12, 43, 230002))),
            ],
            options={
                'db_table': 'Ad_Data',
            },
        ),
    ]
