# Generated by Django 2.1.7 on 2019-04-14 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20190414_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrequirement',
            name='Posted_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 19, 21, 6, 497035)),
        ),
    ]
